### ISSUE TITLE
Problems loading share count for Twitter

### ISSUE THREAD

**Issue by mschilder** [enjoyiacm/goodshare.js#10]
Hi!

Great piece of code. Small issue with Twitter thought. 

When looking at our site (and also on goodshare.ru), it appears that the ShareCount for Twitter can not be loaded. The console reports the following error:

Failed to load resource: the server responded with a status of 410 (Gone)
https://cdn.api.twitter.com/1/urls/count.json?url=http%3A%2F%2Fgoodshare.ru%2F&callback=jQuery11130405707340920344_1450355410033&_=1450355410034

**Comment by enjoyiacm** [comment]
Yes. Since 21 Nov 2015 Twitter official drop support counters for twit button.

Instruction how to get Twitter share count — https://github.com/enjoyiacm/goodshare.js#instruction-how-to-get-twitter-share-counter-after-api-11-changes
