### ISSUE TITLE
Bad Request при запросе "поделиться" в ВК на отдельных страницах

### ISSUE THREAD

**Issue by zoltanmd** [enjoyiacm/goodshare.js#17]
При нажатии на кнопку "Поделиться в ВК" открывается пустое окно с заголовком "400 Bad Request" (http://vk.com/err400.html). Но не везде, а примерно на половине страниц. 
Пример "сбойной" страницы: http://kurantynew.ru/new/2016/04/15/a-mne-letat-ohota/
и "нормальной": http://kurantynew.ru/new/2016/03/25/dialog-o-poligone/

**Comment by enjoyiacm** [comment]
Проверьте код этой страницы. Проблема в нём, а не в goodshare.js.

**Comment by padurets** [comment]
@zoltanmd, отпишите пожалуйста как решили проблему

**Comment by zoltanmd** [comment]
@padurets , я не особо кодер, да и на php, как говорится, "со словарем". Поэтому, возможно, решение у меня кривое, или захожу не с той стороны. Но...
У меня установлен SEO-плагин All-In-One-SEO-Pack, который генерирует содержимое для тегов opengraph. В файле aioseop_opengraph.php дважды задается значение для длины описания:

`if ( empty( $description ) && $first_page && ( ! empty( $this->options['aiosp_opengraph_generate_descriptions'] ) ) && ! empty( $post ) && ! empty( $post->post_content ) && ! post_password_required( $post ) ) {
					$description = $aiosp->trim_excerpt_without_filters( $aiosp->internationalize( preg_replace( '/\s+/', ' ', $post->post_content ) ), 1000 );`

и

`if ( ! empty( $description ) ) {
				$description = $aiosp->internationalize( preg_replace( '/\s+/', ' ', $description ) );
				if ( ! empty( $this->options['aiosp_opengraph_description_shortcodes'] ) ) {
					$description = do_shortcode( $description );
				}
				$description = $aiosp->trim_excerpt_without_filters( $description, 1000 );`

Вместо 1000 поставил 500 и все заработало.
Повторюсь, возможно это некорректное решение, возможно значение может быть и больше, но меня устроило. Единственное неудобство в том, что приходится после обновления плагина прописывать значения заново.

**Comment by padurets** [comment]
@zoltanmd, большое спасибо за наводку!
Проблема в том, что рекомендуемая длинна url = [2000 символов](http://stackoverflow.com/a/417184/4917700), и в случае слишком длинного передаваемого описания все валится.

@koddr, полагаю в плагине имеет смысл сделать опцию для указания максимальной длинны описания, чтобы текст обрезался и добавлялся какой-то суффикс, например '...'
![](https://api.monosnap.com/rpc/file/download?id=iotIJv73VZT09WQvTfRxhrATYbtLAK)

**Comment by koddr** [comment]
@padurets по стандартам, в подобных мета тегах, из которых берётся информация для description, не должно быть больше 255 символов. Поэтому особого смысла в подобной опции просто нет, если следовать стандарту.

Опять же, вы говорите про старую jQuery версию, которую мы, разработчики, более не поддерживаем (начиная с 4.0.0).
