### ISSUE TITLE
No 'decortion options'

### ISSUE THREAD

**Issue by Frankie3142** [enjoyiacm/goodshare.js#19]
Hi
You say "This example shows one of decoration options with all supported social networks" and follow it with a beautiful picture showing buttons and icons.
However, there is no documentation on this feature anywhere and I can see nothing in the code that would generate it. How do you activate this 'option' please?

Thank you.

Frankie

**Comment by enjoyiacm** [comment]
See after this picture. HTML code do this, copy and be happy!

**Comment by Frankie3142** [comment]
No it doesn't. It creates it **minus the beautiful icons** I asked about.
See here: [WHAT YOUR CODE ACTUALLY PRODUCES](http://advancedvirtual.com/ipcamera/Capture.JPG)

Do you have any code that makes the picture icons you advertised?

Thank you.

**Comment by enjoyiacm** [comment]
You may download icons here: http://goodshare.ru/download/fontello-goodshare.zip
