### ISSUE TITLE
Add to jsdelivr cdn

### ISSUE THREAD

**Issue by stephenjamieson** [enjoyiacm/goodshare.js#2]
https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

Would be nice to have this here as well as rawgit

**Comment by enjoyiacm** [comment]
Thx. Add to "To Do" list.

**Comment by enjoyiacm** [comment]
Hi, @stephenjamieson 

Finally.. Today we added ``goodshare.js`` to jsDelivr!
Our page here: http://www.jsdelivr.com/projects/jquery.goodshare.js

P.S. Use latest version: ``https://cdn.jsdelivr.net/jquery.goodshare.js/latest/goodshare.min.js``
