### ISSUE TITLE
Получение количества расшаренных 

### ISSUE THREAD

**Issue by TsarS** [enjoyiacm/goodshare.js#21]
Добрый день. А можно получить общее количество всех расшаренных (например фотографий) в одном месте? Ну т.е. все фотографии в фейсбук расшарили 25 раз?

**Comment by enjoyiacm** [comment]
Добрый. У goodshare.js открытый код, можете дописывать любые улучшения, какие пожелаете, — достаточно просто сделать Fork нашего репозитория.
