### ISSUE TITLE
Set minimum shares for share count

### ISSUE THREAD

**Issue by Mattvic** [enjoyiacm/goodshare.js#8]
The share count is a great feature too increase shares, but if an article has 0 shares it can have an opposite effect. 

Is there a way to display share counts only when there is at least 1 share? (Or maybe let the user define a minimum number of shares before showing the share count). 

Thanks for this great plugin, it´s easily the best social sharing plugin I´ve found!

**Comment by enjoyiacm** [comment]
Hello, @Mattvic 

Thank you for using goodshare.js!

For example, Facebook counter ([lines 447-456](https://github.com/enjoyiacm/goodshare.js/blob/master/goodshare.js#L447-L456)):

```javascript
/*
 *  Share counter > Facebook
 *  @see https://developers.facebook.com
 */
if (existCount('[data-counter="fb"]')) {
  $.getJSON('http://graph.facebook.com/?id=' + encodeURIComponent(location.href) + '&callback=?', function(response) {
    if (response.shares >= 1  && response.shares !== undefined) {
      $('[data-counter="fb"]').text(roundCount(response.shares));
    }
    else {
      $('[data-counter="fb"]').remove();
    }
  });
};
```

**Comment by Mattvic** [comment]
Great thanks!!
