### ISSUE TITLE
The parameters do not work for facebook?

### ISSUE THREAD

**Issue by andrey-hohlov** [enjoyiacm/goodshare.js#9]
Hi!
I'm using button with this mark-up:
```html
<button class="goodshare"
        data-type="fb"
        data-url="http://hohlov.pro/goodshare/page2.html"
        data-title="Second page (data)"
        data-text="Second page description(data)"
        data-image="http://hohlov.pro/goodshare/og2.png">
    fb
</button>
```

For VK it work's fine.
But for Facebook - don't work.

If page in  data-url exist - it's get params from that page. If don't exist - get params from 404 error.

Live example: http://hohlov.pro/goodshare/

**Comment by andrey-hohlov** [comment]
And now i look in code...

And then looking on SO:
http://stackoverflow.com/questions/20956229/has-facebook-sharer-php-changed-to-no-longer-accept-detailed-parameters
http://stackoverflow.com/questions/11868291/google-plus-share-and-parameters-in-url

Bad :( Last time when i use this params works.

**Comment by enjoyiacm** [comment]
@andrey-hohlov may be trouble with Facebook cache? Try this dev tools to clear this: https://developers.facebook.com/tools/debug/
